import "dotenv/config";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

if (!process.env.RESEND_API_KEY) {
  throw new Error("Missing RESEND_API_KEY in .env");
}

const SEGMENT_ID = "8d970073-10a7-4431-9264-176e4378d6d3";

const emails = [
  "13odettefj@gmail.com",
  "3nr1qv3@gmail.com",
  "9511017900a@gmail.com",
  "abril.osuna1@icloud.com",
  "aeds7985@gmail.com",
  "alex2592.x@gmail.com",
  "amandavmoran096@gmail.com",
  "anahivdh@gmail.com",
  "andrea.huber@ucalgary.ca",
  "andres24-02@hotmail.com",
  "andy_dgg@hotmail.com",
  "angelicaserrano@shaw.ca",
  "angelina.nair@gmail.com",
  "angelxmipito@gmail.com",
  "ara13lab@gmail.com",
  "aracelypuga@hotmail.com",
  "aramichelle@gmail.com",
  "ariuxss80@gmail.com",
  "arlettedenton@outlook.com",
  "asenetfragoso@hotmail.com",
  "beto_brooks1@hotmail.com",
  "blanca.may.c@hotmail.com",
  "calexia95@yahoo.com",
  "canalatinarn@gmail.com",
  "carloscor1114@gmail.com",
  "carol78ag@hotmail.com",
  "carozubieta1@hotmail.com",
  "chiiaki@gmail.com",
  "chile2@icloud.com",
  "cintia.j.lopez@gmail.com",
  "claudnavarro@gmail.com",
  "dlararivas94@gmail.com",
  "dy.ivette@gmail.com",
  "eli_thh1@hotmail.com",
  "eliseoesquivelc@gmail.com",
  "enreding4@gmail.com",
  "eriscit@icloud.com",
  "essaau_07@hotmail.es",
  "fercho88ferny@gmail.com",
  "franciscoautoyyc@outloo.com",
  "franciscogato13@hotmail.com",
  "frida.corleto@gmail.com",
  "gchinea4@gmail.com",
  "ghafarsamadi44@gmail.com",
  "gonzalezjuly986@gmail.com",
  "heidi.lickon@gmail.com",
  "helenyanettdieguez@gmail.com",
  "hibahg26g@gmail.com",
  "ibarra_aldair@icloud.com",
  "ifybioma@gmail.com",
  "ismaelhgg@gmail.com",
  "jasaheba@live.com.mx",
  "jdmrqz21@gmail.com",
  "jeremy.p.lester@hotmail.com",
  "jessicasantander123@gmail.com",
  "jisela1987_@hotmail.com",
  "juegosycuenta052@gmail.com",
  "k.j.j.waghorn@gmail.com",
  "karabinlydia@yahoo.ca",
  "karlaaven16@gmail.com",
  "laracerv11@gmail.com",
  "laupequitas87@gmail.com",
  "lilia.rios79@gmail.com",
  "lino0412@hotmail.com",
  "lumartin2506@gmail.com",
  "mariobr2012@gmail.com",
  "marlene1041@hotmail.com",
  "mcmq25@gmail.com",
  "mery123105m@gmail.com",
  "mfsandoval123@gmail.com",
  "michellegin9@gmail.com",
  "pablin1991260220@gmail.com",
  "pablo.noriega@sprung.com",
  "paola.petralia1@gmail.com",
  "paula_diaz1996@outlook.com",
  "renegus@gmail.com",
  "rohyna.issaqzai@hotmail.com",
  "rperezag77@gmail.com",
  "santoshdezlj@gmail.com",
  "sarah_0312@hotmail.com",
  "sharyscid21@gmail.com",
  "sr3399387@gmail.com",
  "starwarjh@gmail.com",
  "tatalemus31@gmail.com",
  "th.selwyn@hotmail.com",
  "tlievano23@gmail.com",
  "vale0011@hotmail.ca",
  "venusivonne@live.com.mx",
  "walter_mendez@icloud.com",
  "x.mendoza93@hotmail.com",
  "xgerka@gmail.com",
  "ye77@hotmail.com",
  "yessi11111@hotmail.com",
  "yoany-14@hotmail.com",
  "zavalajenny6@gmail.com",
  "luissanchezmoran3@gmail.com",
  "hn.cruz98@gmail.com",
  "amandacarbn@gmail.com",
  "su.gonzcas@gmail.com",
  "merakedu@gmail.com",
  "tfariaz@icloud.com",
  "abrahamnvmd@gmail.com",
  "leah.lavoie@calgarydiocese.ca",
  "tony.ornelas28@gmail.com",
  "gutierrez_blanca@hotmail.ca",
  "dav14907@gmail.com",
  "lesslie.geraldine@gmail.com",
  "rosamaria.mar@icloud.com",
  "mgalfonsin@hotmail.com",
  "jessyroos@gmail.com",
  "anais213@outlook.com",
  "pamelamaroib@gmail.com",
  "evolgard@yahoo.com",
  "zuleymalozano@gmail.com",
  "mariel.fh2090@gmail.com",
  "monicasanchez.b@hotmail.com",
  "paosan1417@gmail.com",
  "kolyam_@hotmail.com",
  "veg1979@hotmail.com",
  "ligiamo17@gmail.com",
  "marisolcastrog88@gmail.com",
  "aaron.lls@outlook.com",
  "abnerblanco1899@gmail.com",
  "abril.cusmex@gmail.com",
  "alexandra.ola.fal@gmail.com",
  "banayeli543@gmail.com",
  "anjanmani47@gmail.com",
  "yalilramirez26@gmail.com",
  "aryroja41@gmail.com",
  "berita_butterfly@hotmail.com",
  "brenda_rb@hotmail.com",
  "tamez.carlos@gmail.com",
  "carolina.i.gonzalez@gmail.com",
  "cmvooys@gmail.com",
  "chelzeacolin@hotmail.com",
  "corykjohnson8@gmail.com",
  "crystal.haddon@gmail.com",
  "dvasq775@mtroyal.ca",
  "danieladiaz2702@gmail.com",
  "niqueyong17@gmail.com",
  "ednita379@hotmail.com",
  "franciscoautoyyc@outlook.com",
  "enzoapp2@gmail.com",
  "erendiraguerrero37@gmail.com",
  "estherjml23@gmail.com",
  "fatimaem06@gmail.com",
  "murillobeltranmarcelagina@gmail.com",
  "harryybrightt@gmail.com",
  "heidiabercrombie@gmail.com",
  "stmargaretgrad2025@gmail.com",
  "f15shorty@hotmail.com",
  "segurajenny01@gmail.com",
  "benitezj@telus.net",
  "luisrodrigo762@gmail.com",
  "mguerere29@gmail.com",
  "lucasm33@learn.cssd.ab.ca",
  "iparraguirre.mercedes@gmail.com",
  "mwavie1971@gmail.com",
  "jimeneztmiguel@gmail.com",
  "natzafra@outlook.com",
  "noecastro.mail@gmail.com",
  "pamebaquedano29@gmail.com",
  "pio.mendoza.j@gmail.com",
  "pardeepkjaswal@gmail.com",
  "pgiles01@gmail.com",
  "poncecarolina1012@gmail.com",
  "reyna_castillo25@hotmail.com",
  "vargas773006@hotmail.com",
  "ritikadua23@gmail.com",
  "rocio.arce.leon@gmail.com",
  "rodolfomona72@gmail.com",
  "gomezutto@gmail.com",
  "rph226@gmail.com",
  "tinashields99@gmail.com",
  "vaaescsocial@gmail.com",
  "ronnie_major@hotmail.com",
  "lisaloerart@gmail.com",
  "clausmexarg@gmail.com",
  "sarahannh609@gmail.com",
  "jeremyloricharliegus@gmail.com",
  "tatalemus31@gmail.con",
  "moralesnena361@gmail.com",
  "kary_krola@hotmail.com",
  "roxanne_290@hotmail.com",
];


async function main() {
  for (const email of emails) {
    try {
      await resend.contacts.create({
        email: email.toLowerCase().trim(),
        audienceId: SEGMENT_ID,
      });

      console.log("✅ Added:", email);
    } catch (err) {
      console.error("❌ Failed:", email, err);
    }

    await new Promise((r) => setTimeout(r, 150));
  }
}


main();