import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "en", title: "English" },
    { name: "es", title: "Español" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "announcementBar",
      title: "Announcement bar (EN)",
      type: "array",
      group: "en",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "announcementBarEs",
      title: "Announcement bar (ES)",
      type: "array",
      group: "es",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "heroTitle",
      title: "Hero title (EN)",
      type: "text",
      group: "en",
      rows: 2,
    }),
    defineField({
      name: "heroTitleEs",
      title: "Hero title (ES)",
      type: "text",
      group: "es",
      rows: 2,
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero subtitle (EN)",
      type: "text",
      group: "en",
      rows: 2,
    }),
    defineField({
      name: "heroSubtitleEs",
      title: "Hero subtitle (ES)",
      type: "text",
      group: "es",
      rows: 2,
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      type: "image",
      group: "settings",
      options: { hotspot: true },
    }),
    defineField({
      name: "referralDiscount",
      title: "Referral discount ($)",
      type: "number",
      group: "settings",
      initialValue: 10,
    }),
    defineField({
      name: "pickupAddress",
      title: "Pickup address",
      type: "string",
      group: "settings",
    }),
    defineField({
      name: "contactPhone",
      title: "Contact phone",
      type: "string",
      group: "settings",
    }),
    defineField({
      name: "contactEmail",
      title: "Contact email",
      type: "string",
      group: "settings",
    }),
    defineField({
      name: "deliveryFreeMinSE",
      title: "Free first delivery for SE Calgary?",
      type: "boolean",
      group: "settings",
      initialValue: true,
    }),
  ],
});
